POST http://localhost:8080/api/enderecos/criar
Content-Type: application/json

{
    "nome_pessoa": "Ronaldo",
    "rua": "Rua José Estácio",
    "bairro": "Santa Efigênia",
    "cep": "08556560"
}

###

GET http://localhost:8080/api/enderecos/selecionarTodos
Content-Type: application/json

###

GET http://localhost:8080/api/enderecos/selecionarUmaPessoa/4
Content-Type: application/json

###

PUT http://localhost:8080/api/enderecos/atualizar/3
Content-Type: application/json

###
DELETE http://localhost:8080/api/enderecos/deletar/14
Content-Type: application/json
